- name: "system_02_file_system | Creating {{ LV_LOG }} volume"
  lvol:
      vg:  "{{ VG_Name }}" 
      lv:  "{{ LV_LOG }}"
      size: "{{ LV_LOG_SIZE }}"
      force: yes

- name: "system_02_file_system | format {{ LV_LOG }} with the xfs filesystem"
  filesystem:
      fstype: "xfs"
      dev: "/dev/{{ VG_Name }}/{{ LV_LOG }}"

- name: "system_02_file_system | Move originale {{ LV_LOG_MNT }} to {{ LV_LOG_MNT }}.old" 
  command: "mv {{ LV_LOG_MNT }} {{ LV_LOG_MNT }}.old && mkdir {{ LV_LOG_MNT }} && mount {{ LV_LOG_MNT }} && cp -Rp {{ LV_LOG_MNT }}.old/* {{ LV_LOG_MNT }}/* "

- name: "system_02_file_system | Create directory {{ LV_LOG_MNT }} if does not exist"
  file:
      path: "{{ LV_LOG_MNT }}"
      state: "directory"
      mode: '0755'

- name: "system_02_file_system | mount the lv {{ LV_LOG }} on {{ LV_LOG_MNT }}"
  mount:
      path: "{{ LV_LOG_MNT }}"
      src: "/dev/{{ VG_Name }}/{{ LV_LOG }}"
      fstype: "xfs"
      state: "mounted"


- name: "system_02_file_system | Move originale data from {{ LV_LOG_MNT }}.old to {{ LV_LOG_MNT }}" 
  command: "mv {{ LV_LOG_MNT }}.old/* {{ LV_LOG_MNT }}/"


