- name: "system_02_file_system | Creating {{ LV_VAR }} volume"
  lvol:
      vg:  "{{ VG_Name }}"
      lv:  "{{ LV_VAR }}"
      size: "{{ LV_VAR_SIZE }}"
      force: yes

- name: "system_02_file_system | format {{ LV_VAR }} with the xfs filesystem"
  filesystem:
      fstype: "xfs"
      dev: "/dev/{{ VG_Name }}/{{ LV_VAR }}"

- name: "system_02_file_system |Move originale {{ LV_VAR_MNT }} to {{ LV_VAR_MNT }}.old" 
  command: "mv {{ LV_VAR_MNT }} {{ LV_VAR_MNT }}.old && mkdir {{ LV_VAR_MNT }} &&  mount {{ LV_VAR_MNT }} && cp -Rp {{ LV_VAR_MNT }}.old/* {{ LV_VAR_MNT }}/ "

- name: "system_02_file_system | Create directory {{ LV_VAR_MNT }} if does not exist"
  file:
      path: "{{ LV_VAR_MNT }}"
      state: "directory"
      mode: '0755'

- name: "system_02_file_system | mount the lv {{ LV_VAR }} on {{ LV_VAR_MNT }}"
  mount:
      path: "{{ LV_VAR_MNT }}"
      src: "/dev/{{ VG_Name }}/{{ LV_VAR }}"
      fstype: "xfs"
      state: "mounted"

- name: "system_02_file_system | Move originale data from {{ LV_VAR_MNT }}.old to {{ LV_VAR_MNT }}" 
  command: "mv {{ LV_VAR_MNT }}.old/* {{ LV_VAR_MNT }}/"